<a href="https://colab.research.google.com/github/yakshithav/internship/blob/master/ml1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

machine learning (scikit learn)

In [0]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

demoData = np.random.randint(10, 100, (10 ,2))
demoData

array([[15, 34],
       [75, 78],
       [95, 88],
       [41, 75],
       [38, 43],
       [90, 28],
       [20, 46],
       [92, 34],
       [91, 50],
       [70, 77]])

In [0]:
demoData = np.random.randint(10, 100, (10 ,2))
demoData

array([[20, 52],
       [68, 19],
       [97, 96],
       [79, 66],
       [66, 83],
       [64, 38],
       [56, 68],
       [46, 26],
       [28, 40],
       [54, 36]])

In [0]:
scalar_model = MinMaxScaler()
scalar_model.fit_transform(demoData)


array([[0.        , 0.42857143],
       [0.62337662, 0.        ],
       [1.        , 1.        ],
       [0.76623377, 0.61038961],
       [0.5974026 , 0.83116883],
       [0.57142857, 0.24675325],
       [0.46753247, 0.63636364],
       [0.33766234, 0.09090909],
       [0.1038961 , 0.27272727],
       [0.44155844, 0.22077922]])

In [0]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

demoData = np.random.randint(1, 500, (20 ,4))
demoData

array([[116, 152, 101, 243],
       [373,  39, 295,   9],
       [ 25, 191, 287, 373],
       [381, 470, 413, 346],
       [415, 223,  97, 221],
       [320,   3,  11, 258],
       [383, 258, 204, 326],
       [243, 107, 117, 266],
       [494, 254,  79, 194],
       [338, 186, 409,  40],
       [125, 471, 158, 218],
       [260, 166, 236, 310],
       [ 17, 270, 201, 151],
       [341, 176,  53, 165],
       [ 50, 482, 491, 488],
       [101,  62, 418, 269],
       [106,  77, 141, 213],
       [263, 466, 419, 256],
       [343,  74, 247,  75],
       [140, 447, 257,  36]])

In [0]:
scalar_model = MinMaxScaler()
feature_data = scalar_model.fit_transform(demoData)
feature_data

array([[0.20754717, 0.31106472, 0.1875    , 0.48851775],
       [0.74633124, 0.07515658, 0.59166667, 0.        ],
       [0.01677149, 0.39248434, 0.575     , 0.75991649],
       [0.76310273, 0.97494781, 0.8375    , 0.70354906],
       [0.83438155, 0.45929019, 0.17916667, 0.44258873],
       [0.63522013, 0.        , 0.        , 0.51983299],
       [0.7672956 , 0.53235908, 0.40208333, 0.66179541],
       [0.47379455, 0.217119  , 0.22083333, 0.53653445],
       [1.        , 0.52400835, 0.14166667, 0.38622129],
       [0.67295597, 0.38204593, 0.82916667, 0.06471816],
       [0.22641509, 0.97703549, 0.30625   , 0.43632568],
       [0.50943396, 0.34029228, 0.46875   , 0.62839248],
       [0.        , 0.55741127, 0.39583333, 0.29645094],
       [0.67924528, 0.3611691 , 0.0875    , 0.3256785 ],
       [0.06918239, 1.        , 1.        , 1.        ],
       [0.17610063, 0.12317328, 0.84791667, 0.54279749],
       [0.18658281, 0.15448852, 0.27083333, 0.42588727],
       [0.51572327, 0.96659708,

In [0]:
import pandas as pd
df = pd.DataFrame(data=feature_data, columns=['k1', 'k2', 'k3', 'labels'])
df

k1        k2        k3    labels
0   0.207547  0.311065  0.187500  0.488518
1   0.746331  0.075157  0.591667  0.000000
2   0.016771  0.392484  0.575000  0.759916
3   0.763103  0.974948  0.837500  0.703549
4   0.834382  0.459290  0.179167  0.442589
5   0.635220  0.000000  0.000000  0.519833
6   0.767296  0.532359  0.402083  0.661795
7   0.473795  0.217119  0.220833  0.536534
8   1.000000  0.524008  0.141667  0.386221
9   0.672956  0.382046  0.829167  0.064718
10  0.226415  0.977035  0.306250  0.436326
11  0.509434  0.340292  0.468750  0.628392
12  0.000000  0.557411  0.395833  0.296451
13  0.679245  0.361169  0.087500  0.325678
14  0.069182  1.000000  1.000000  1.000000
15  0.176101  0.123173  0.847917  0.542797
16  0.186583  0.154489  0.270833  0.425887
17  0.515723  0.966597  0.850000  0.515658
18  0.683438  0.148225  0.491667  0.137787
19  0.257862  0.926931  0.512500  0.056367

In [0]:
X = df[['k1', 'k2', 'k3']]
y = df['labels']
X

k1        k2        k3
0   0.207547  0.311065  0.187500
1   0.746331  0.075157  0.591667
2   0.016771  0.392484  0.575000
3   0.763103  0.974948  0.837500
4   0.834382  0.459290  0.179167
5   0.635220  0.000000  0.000000
6   0.767296  0.532359  0.402083
7   0.473795  0.217119  0.220833
8   1.000000  0.524008  0.141667
9   0.672956  0.382046  0.829167
10  0.226415  0.977035  0.306250
11  0.509434  0.340292  0.468750
12  0.000000  0.557411  0.395833
13  0.679245  0.361169  0.087500
14  0.069182  1.000000  1.000000
15  0.176101  0.123173  0.847917
16  0.186583  0.154489  0.270833
17  0.515723  0.966597  0.850000
18  0.683438  0.148225  0.491667
19  0.257862  0.926931  0.512500

In [0]:
X = df[['k1', 'k2', 'k3']]
y = df['labels']
y

0     0.488518
1     0.000000
2     0.759916
3     0.703549
4     0.442589
5     0.519833
6     0.661795
7     0.536534
8     0.386221
9     0.064718
10    0.436326
11    0.628392
12    0.296451
13    0.325678
14    1.000000
15    0.542797
16    0.425887
17    0.515658
18    0.137787
19    0.056367
Name: labels, dtype: float64

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)
X_train.shape

(14, 3)

load the iris data set and check the features

In [16]:
from sklearn.datasets import load_iris
iris=load_iris()
type(iris)
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [17]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [18]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [19]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [20]:
print(type(iris.data))
print(type(iris.target))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [21]:
print(iris.data.shape)

(150, 4)


In [26]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=4)

print(X_train.shape)
print(X_test.shape)


(16, 3)
(4, 3)


In [27]:
print(y_train.shape)
print(y_test.shape)

(16,)
(4,)


In [43]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=4)

print(X_train.shape)
print(X_test.shape)


(16, 3)
(4, 3)


In [44]:
from sklearn.neighbors import KNeighborsClassifier
 
from sklearn import metrics

k_range = range(1,26)
scores = {}
scores_list = []
for k in k_range:
        knn = KNeighborsClassifier(n_neighbors=k)
        knn.fit(X_train,y_train)
        y_pred=knn.predict(X_test)
        scores[k] = metrics.accuracy_score(y_test,y_pred)
        scores_list.append(metrics.accuracy_score(y_test,y_pred))
        
scores


ValueError: ignored