<a href="https://colab.research.google.com/github/yakshithav/internship/blob/master/ml1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

machine learning (scikit learn)

In [0]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

demoData = np.random.randint(10, 100, (10 ,2))
demoData

array([[15, 34],
       [75, 78],
       [95, 88],
       [41, 75],
       [38, 43],
       [90, 28],
       [20, 46],
       [92, 34],
       [91, 50],
       [70, 77]])

In [0]:
demoData = np.random.randint(10, 100, (10 ,2))
demoData

array([[20, 52],
       [68, 19],
       [97, 96],
       [79, 66],
       [66, 83],
       [64, 38],
       [56, 68],
       [46, 26],
       [28, 40],
       [54, 36]])

In [0]:
scalar_model = MinMaxScaler()
scalar_model.fit_transform(demoData)


array([[0.        , 0.42857143],
       [0.62337662, 0.        ],
       [1.        , 1.        ],
       [0.76623377, 0.61038961],
       [0.5974026 , 0.83116883],
       [0.57142857, 0.24675325],
       [0.46753247, 0.63636364],
       [0.33766234, 0.09090909],
       [0.1038961 , 0.27272727],
       [0.44155844, 0.22077922]])

In [4]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

demoData = np.random.randint(1, 500, (20 ,4))
demoData

array([[116, 152, 101, 243],
       [373,  39, 295,   9],
       [ 25, 191, 287, 373],
       [381, 470, 413, 346],
       [415, 223,  97, 221],
       [320,   3,  11, 258],
       [383, 258, 204, 326],
       [243, 107, 117, 266],
       [494, 254,  79, 194],
       [338, 186, 409,  40],
       [125, 471, 158, 218],
       [260, 166, 236, 310],
       [ 17, 270, 201, 151],
       [341, 176,  53, 165],
       [ 50, 482, 491, 488],
       [101,  62, 418, 269],
       [106,  77, 141, 213],
       [263, 466, 419, 256],
       [343,  74, 247,  75],
       [140, 447, 257,  36]])

In [5]:
scalar_model = MinMaxScaler()
feature_data = scalar_model.fit_transform(demoData)
feature_data

array([[0.20754717, 0.31106472, 0.1875    , 0.48851775],
       [0.74633124, 0.07515658, 0.59166667, 0.        ],
       [0.01677149, 0.39248434, 0.575     , 0.75991649],
       [0.76310273, 0.97494781, 0.8375    , 0.70354906],
       [0.83438155, 0.45929019, 0.17916667, 0.44258873],
       [0.63522013, 0.        , 0.        , 0.51983299],
       [0.7672956 , 0.53235908, 0.40208333, 0.66179541],
       [0.47379455, 0.217119  , 0.22083333, 0.53653445],
       [1.        , 0.52400835, 0.14166667, 0.38622129],
       [0.67295597, 0.38204593, 0.82916667, 0.06471816],
       [0.22641509, 0.97703549, 0.30625   , 0.43632568],
       [0.50943396, 0.34029228, 0.46875   , 0.62839248],
       [0.        , 0.55741127, 0.39583333, 0.29645094],
       [0.67924528, 0.3611691 , 0.0875    , 0.3256785 ],
       [0.06918239, 1.        , 1.        , 1.        ],
       [0.17610063, 0.12317328, 0.84791667, 0.54279749],
       [0.18658281, 0.15448852, 0.27083333, 0.42588727],
       [0.51572327, 0.96659708,