<a href="https://colab.research.google.com/github/yakshithav/internship/blob/master/np1_ipny.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [0]:
a.shape

(3, 5)

In [0]:
a.ndim

2

In [0]:
a.dtype.name

'int64'

In [0]:
a.itemsize

8

In [7]:
a.size

15

In [8]:
type(a)

numpy.ndarray

In [9]:
b=np.array([6,7,8])
b

array([6, 7, 8])

Three dimensional

In [19]:
import numpy as np
c=np.arange(18).reshape(2,3,3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [21]:
c.ndim

3

In [22]:
c.shape

(2, 3, 3)

In [23]:
c.dtype.name

'int64'

Array Creation

In [24]:
import numpy as np
a=np.array([2,3,4])
a

array([2, 3, 4])

In [25]:
a.dtype

dtype('int64')

In [26]:
e=np.array([1.2,3.5,5.1])
e.dtype

dtype('float64')

In [28]:
b=np.array([(1.5,2,3),(4,5,6)])
b
           

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [29]:
c=np.array([[1,2],[3,4]],dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [34]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

Creating Zeros

In [36]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [39]:
np.empty((1,3))

array([[2.4927612e-316, 0.0000000e+000, 0.0000000e+000]])

In [40]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [41]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])