<a href="https://colab.research.google.com/github/yakshithav/internship/blob/master/np1_ipny.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [0]:
a.shape

(3, 5)

In [0]:
a.ndim

2

In [0]:
a.dtype.name

'int64'

In [0]:
a.itemsize

8

In [0]:
a.size

15

In [0]:
type(a)

numpy.ndarray

In [0]:
b=np.array([6,7,8])
b

array([6, 7, 8])

Three dimensional

In [0]:
import numpy as np
c=np.arange(18).reshape(2,3,3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [0]:
c.ndim

3

In [0]:
c.shape

(2, 3, 3)

In [0]:
c.dtype.name

'int64'

Array Creation

In [0]:
import numpy as np
a=np.array([2,3,4])
a

array([2, 3, 4])

In [0]:
a.dtype

dtype('int64')

In [0]:
e=np.array([1.2,3.5,5.1])
e.dtype

dtype('float64')

In [0]:
b=np.array([(1.5,2,3),(4,5,6)])
b
           

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [0]:
c=np.array([[1,2],[3,4]],dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [0]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

Creating Zeros

In [0]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [0]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [0]:
np.empty((1,3))

array([[2.4927612e-316, 0.0000000e+000, 0.0000000e+000]])

In [0]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [0]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [0]:
from numpy import pi
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [0]:
x=np.linspace(0,2*pi,100)
f=np.sin(x)
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

Printing arrays.

In [0]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [2]:
import numpy as np
b=np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [3]:
c=np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [4]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [5]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


Basic operation

In [7]:
a=np.array([20,30,40,50])
b=np.arange(4)
b

array([0, 1, 2, 3])

In [8]:
c=a-b
c

array([20, 29, 38, 47])

In [9]:
b**2

array([0, 1, 4, 9])

In [10]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [11]:
a<35

array([ True,  True, False, False])

In [13]:
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])
A*B

array([[2, 0],
       [0, 4]])

In [14]:
A@B

array([[5, 4],
       [3, 4]])

In [15]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [17]:
a=np.ones((2,3),dtype=int)
b=np.random.random((2,3))
a*=3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [18]:
b+=a
b

array([[3.71231041, 3.83014672, 3.08648129],
       [3.78295277, 3.28871054, 3.32910073]])

In [19]:
a+=b

TypeError: ignored

In [23]:
from numpy import pi
a=np.ones(3,dtype=np.int32)
b=np.linspace(0,pi,3)
b.dtype.name

'float64'

In [24]:
c=a+b
c

array([1.        , 2.57079633, 4.14159265])

In [25]:
c.dtype.name

'float64'

In [26]:
d=np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [27]:
d.dtype.name

'complex128'

In [29]:
a=np.random.random((2,3))
a

array([[0.16278714, 0.9482673 , 0.65126894],
       [0.81615387, 0.24598642, 0.37261724]])

In [30]:
a.sum()

3.1970809051674847

In [31]:
a.min()

0.16278713734204542

In [32]:
a.max()

0.9482673037123346

In [33]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [35]:
b.min(axis=1)

array([0, 4, 8])

In [36]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])