<a href="https://colab.research.google.com/github/yakshithav/internship/blob/master/np2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Universal Functions

In [1]:
import numpy as np
B=np.arange(3)
B

array([0, 1, 2])

In [3]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [4]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [5]:
C=np.array([2.,-1.,4.])
np.add(B,C)

array([2., 0., 6.])

Indexing,Slicing and Iterating

In [6]:
a=np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [7]:
a[2]

8

In [9]:
a[2:5]

array([ 8, 27, 64])

In [10]:
a[:6:2]

array([ 0,  8, 64])

In [13]:
a[-1]

729

In [14]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [15]:
a[: : -1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [0]:
a[:6:2]=-1000

In [17]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [19]:
for i in a:
  print(i**(1/3.))

nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  
