<a href="https://colab.research.google.com/github/yakshithav/internship/blob/master/np2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Universal Functions

In [1]:
import numpy as np
B=np.arange(3)
B

array([0, 1, 2])

In [3]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [4]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [5]:
C=np.array([2.,-1.,4.])
np.add(B,C)

array([2., 0., 6.])

Indexing,Slicing and Iterating

In [6]:
a=np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [49]:
a[:9:2]

array([-1000, -1000, -1000,   216,   512])

In [7]:
a[2]

8

In [9]:
a[2:5]

array([ 8, 27, 64])

In [10]:
a[:6:2]

array([ 0,  8, 64])

In [13]:
a[-1]

729

In [14]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [15]:
a[: : -1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [44]:
a[:9:2]

array([-1000, -1000, -1000,   216,   512])

In [45]:
a[:6:2]

array([-1000, -1000, -1000])

In [30]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [43]:
a[:9:2]

array([-1000, -1000, -1000,   216,   512])

In [19]:
for i in a:
  print(i**(1/3.))

nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [23]:
a[:]

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

iteration

In [24]:
for row in a:
  print(row)

-1000
1
-1000
27
-1000
125
216
343
512
729


In [25]:
for column in a:
  print(column)

-1000
1
-1000
27
-1000
125
216
343
512
729


In [26]:
def f(x,y):
  return 10*x+y

b=np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [32]:
b[2,3]

23

In [33]:
b[0:5,1]

array([ 1, 11, 21, 31, 41])

In [34]:
b[:,1]

array([ 1, 11, 21, 31, 41])

In [36]:
b[1:3,:1]

array([[10],
       [20]])

In [38]:
b[2,1]

21

In [40]:
b[-10]

array([40, 41, 42, 43])

In [41]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [42]:
b[-1,:]

array([40, 41, 42, 43])

N-dimenional array

In [52]:
d3_array=np.array([[[0,1],
                  [2,3] ],
                  [[4,5],
                  [6,7]]])
d3_array

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [53]:
d3_array[0,1,0]

2

In [55]:
d3_array[:,0,0]

array([0, 4])

In [56]:
d3_array[1]

array([[4, 5],
       [6, 7]])

In [57]:
d3_array[1,:,:]

array([[4, 5],
       [6, 7]])

In [58]:
d3_array[0]

array([[0, 1],
       [2, 3]])

In [65]:
d3_array[1:,1,1]

array([7])

In [67]:
d3_array[1,1:,1]

array([7])

In [70]:
d3_array[1,1,1:]

array([7])