<a href="https://colab.research.google.com/github/yakshithav/internship/blob/master/np2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Universal Functions

In [1]:
import numpy as np
B=np.arange(3)
B

array([0, 1, 2])

In [3]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [4]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [5]:
C=np.array([2.,-1.,4.])
np.add(B,C)

array([2., 0., 6.])

Indexing,Slicing and Iterating

In [6]:
a=np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [49]:
a[:9:2]

array([-1000, -1000, -1000,   216,   512])

In [7]:
a[2]

8

In [9]:
a[2:5]

array([ 8, 27, 64])

In [10]:
a[:6:2]

array([ 0,  8, 64])

In [13]:
a[-1]

729

In [14]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [15]:
a[: : -1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [44]:
a[:9:2]

array([-1000, -1000, -1000,   216,   512])

In [45]:
a[:6:2]

array([-1000, -1000, -1000])

In [30]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [43]:
a[:9:2]

array([-1000, -1000, -1000,   216,   512])

In [19]:
for i in a:
  print(i**(1/3.))

nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [23]:
a[:]

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

iteration

In [24]:
for row in a:
  print(row)

-1000
1
-1000
27
-1000
125
216
343
512
729


In [25]:
for column in a:
  print(column)

-1000
1
-1000
27
-1000
125
216
343
512
729


In [26]:
def f(x,y):
  return 10*x+y

b=np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [32]:
b[2,3]

23

In [33]:
b[0:5,1]

array([ 1, 11, 21, 31, 41])

In [34]:
b[:,1]

array([ 1, 11, 21, 31, 41])

In [36]:
b[1:3,:1]

array([[10],
       [20]])

In [38]:
b[2,1]

21

In [40]:
b[-10]

array([40, 41, 42, 43])

In [41]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [42]:
b[-1,:]

array([40, 41, 42, 43])

N-dimenional array

In [52]:
d3_array=np.array([[[0,1],
                  [2,3] ],
                  [[4,5],
                  [6,7]]])
d3_array

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [53]:
d3_array[0,1,0]

2

In [55]:
d3_array[:,0,0]

array([0, 4])

In [56]:
d3_array[1]

array([[4, 5],
       [6, 7]])

In [57]:
d3_array[1,:,:]

array([[4, 5],
       [6, 7]])

In [58]:
d3_array[0]

array([[0, 1],
       [2, 3]])

In [65]:
d3_array[1:,1,1]

array([7])

In [67]:
d3_array[1,1:,1]

array([7])

In [70]:
d3_array[1,1,1:]

array([7])

3-d shape

In [73]:
arr=np.array([[[0,1,2],
              [3,4,5],
              [6,7,8]],
              
             [[9,10,11],
             [12,13,14],
             [15,16,17]],
              
             [[18,19,20],
             [21,22,23],
             [24,25,26]]])
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [74]:
arr[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [75]:
arr[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
arr[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [78]:
c=np.array([[[0,1,2],
           [10,12,13]],
          [[100,101,102],
          [110,112,113]]])
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [79]:
c.shape

(2, 2, 3)

In [81]:
c[1,...]

array([[100, 101, 102],
       [110, 112, 113]])

In [83]:
c[...,2]

array([[  2,  13],
       [102, 113]])

In [84]:
c[0,...]

array([[ 0,  1,  2],
       [10, 12, 13]])

In [85]:
for row in b:
  print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [87]:
for element in b.flat:
  print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


shape manipulation

In [88]:
a=np.floor(10*np.random.random((3,4)))
a

array([[3., 7., 0., 6.],
       [3., 1., 0., 3.],
       [6., 2., 0., 7.]])

In [89]:
a.shape

(3, 4)

In [90]:
a.ravel()

array([3., 7., 0., 6., 3., 1., 0., 3., 6., 2., 0., 7.])

In [91]:
a.reshape(6,2)

array([[3., 7.],
       [0., 6.],
       [3., 1.],
       [0., 3.],
       [6., 2.],
       [0., 7.]])

In [92]:
a.T

array([[3., 3., 6.],
       [7., 1., 2.],
       [0., 0., 0.],
       [6., 3., 7.]])

In [93]:
a.T.shape

(4, 3)

In [94]:
a.shape

(3, 4)

In [95]:
a

array([[3., 7., 0., 6.],
       [3., 1., 0., 3.],
       [6., 2., 0., 7.]])

In [96]:
a.resize((2,6))
a

array([[3., 7., 0., 6., 3., 1.],
       [0., 3., 6., 2., 0., 7.]])

In [97]:
a.reshape(3,-1)

array([[3., 7., 0., 6.],
       [3., 1., 0., 3.],
       [6., 2., 0., 7.]])

stacking together different arrays

In [98]:
a=np.floor(10*np.random.random((2,2)))
a

array([[6., 0.],
       [3., 1.]])

In [99]:
b=np.floor(10*np.random.random((2,2)))
b

array([[3., 4.],
       [4., 9.]])

In [100]:
np.vstack((a,b))

array([[6., 0.],
       [3., 1.],
       [3., 4.],
       [4., 9.]])

In [101]:
np.hstack((a,b))

array([[6., 0., 3., 4.],
       [3., 1., 4., 9.]])

In [102]:
from numpy import newaxis
np.column_stack((a,b))

array([[6., 0., 3., 4.],
       [3., 1., 4., 9.]])

In [104]:
a=np.array([4.,2.])
b=np.array([3.,8.])
np.column_stack((a,b))

array([[4., 3.],
       [2., 8.]])

In [105]:
np.hstack((a,b))

array([4., 2., 3., 8.])

In [106]:
a[:,newaxis]

array([[4.],
       [2.]])

In [107]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [109]:
np.hstack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [110]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

Splitting one array into several smaller ones

In [111]:
a=np.floor(10*np.random.random((2,12)))
a

array([[1., 7., 0., 5., 5., 9., 4., 8., 6., 3., 2., 4.],
       [1., 4., 9., 5., 6., 1., 7., 2., 5., 9., 5., 8.]])

In [112]:
np.hsplit(a,3)

[array([[1., 7., 0., 5.],
        [1., 4., 9., 5.]]), array([[5., 9., 4., 8.],
        [6., 1., 7., 2.]]), array([[6., 3., 2., 4.],
        [5., 9., 5., 8.]])]

In [113]:
np.hsplit(a,(3,4))

[array([[1., 7., 0.],
        [1., 4., 9.]]), array([[5.],
        [5.]]), array([[5., 9., 4., 8., 6., 3., 2., 4.],
        [6., 1., 7., 2., 5., 9., 5., 8.]])]

copies and values

no copy at all

In [114]:
a=np.arange(12)
b=a
b is a

True

In [115]:
b.shape=3,4
a.shape

(3, 4)

In [126]:
def f(x):
    print(id(x))
  
id(a)  

139936521104640

In [127]:
f(a) 

139936521104640


view or shallow copy

In [128]:
c=a.view()
c is a

False

In [129]:
c.base is a

True

In [130]:
c.flags.owndata

False

In [131]:
c.shape=2,6
a.shape

(3, 4)

In [132]:
c[0,4]=1234
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [135]:
s=a[: , 1:3]
s[:]=10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

deep copy

In [0]:
d=a.copy