<a href="https://colab.research.google.com/github/yakshithav/internship/blob/master/np2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Universal Functions

In [0]:
import numpy as np
B=np.arange(3)
B

array([0, 1, 2])

In [0]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [0]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [0]:
C=np.array([2.,-1.,4.])
np.add(B,C)

array([2., 0., 6.])

Indexing,Slicing and Iterating

In [0]:
a=np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [0]:
a[:9:2]

array([-1000, -1000, -1000,   216,   512])

In [0]:
a[2]

8

In [0]:
a[2:5]

array([ 8, 27, 64])

In [0]:
a[:6:2]

array([ 0,  8, 64])

In [0]:
a[-1]

729

In [0]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [0]:
a[: : -1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [0]:
a[:9:2]

array([-1000, -1000, -1000,   216,   512])

In [0]:
a[:6:2]

array([-1000, -1000, -1000])

In [0]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [0]:
a[:9:2]

array([-1000, -1000, -1000,   216,   512])

In [0]:
for i in a:
  print(i**(1/3.))

nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [0]:
a[:]

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

iteration

In [0]:
for row in a:
  print(row)

-1000
1
-1000
27
-1000
125
216
343
512
729


In [0]:
for column in a:
  print(column)

-1000
1
-1000
27
-1000
125
216
343
512
729


In [0]:
def f(x,y):
  return 10*x+y

b=np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [0]:
b[2,3]

23

In [0]:
b[0:5,1]

array([ 1, 11, 21, 31, 41])

In [0]:
b[:,1]

array([ 1, 11, 21, 31, 41])

In [0]:
b[1:3,:1]

array([[10],
       [20]])

In [0]:
b[2,1]

21

In [0]:
b[-10]

array([40, 41, 42, 43])

In [0]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [0]:
b[-1,:]

array([40, 41, 42, 43])

N-dimenional array

In [0]:
d3_array=np.array([[[0,1],
                  [2,3] ],
                  [[4,5],
                  [6,7]]])
d3_array

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [0]:
d3_array[0,1,0]

2

In [0]:
d3_array[:,0,0]

array([0, 4])

In [0]:
d3_array[1]

array([[4, 5],
       [6, 7]])

In [0]:
d3_array[1,:,:]

array([[4, 5],
       [6, 7]])

In [0]:
d3_array[0]

array([[0, 1],
       [2, 3]])

In [0]:
d3_array[1:,1,1]

array([7])

In [0]:
d3_array[1,1:,1]

array([7])

In [0]:
d3_array[1,1,1:]

array([7])

3-d shape

In [0]:
arr=np.array([[[0,1,2],
              [3,4,5],
              [6,7,8]],
              
             [[9,10,11],
             [12,13,14],
             [15,16,17]],
              
             [[18,19,20],
             [21,22,23],
             [24,25,26]]])
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [0]:
arr[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [0]:
arr[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [0]:
arr[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [0]:
c=np.array([[[0,1,2],
           [10,12,13]],
          [[100,101,102],
          [110,112,113]]])
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [0]:
c.shape

(2, 2, 3)

In [0]:
c[1,...]

array([[100, 101, 102],
       [110, 112, 113]])

In [0]:
c[...,2]

array([[  2,  13],
       [102, 113]])

In [0]:
c[0,...]

array([[ 0,  1,  2],
       [10, 12, 13]])

In [0]:
for row in b:
  print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [0]:
for element in b.flat:
  print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


shape manipulation

In [0]:
a=np.floor(10*np.random.random((3,4)))
a

array([[3., 7., 0., 6.],
       [3., 1., 0., 3.],
       [6., 2., 0., 7.]])

In [0]:
a.shape

(3, 4)

In [0]:
a.ravel()

array([3., 7., 0., 6., 3., 1., 0., 3., 6., 2., 0., 7.])

In [0]:
a.reshape(6,2)

array([[3., 7.],
       [0., 6.],
       [3., 1.],
       [0., 3.],
       [6., 2.],
       [0., 7.]])

In [0]:
a.T

array([[3., 3., 6.],
       [7., 1., 2.],
       [0., 0., 0.],
       [6., 3., 7.]])

In [0]:
a.T.shape

(4, 3)

In [0]:
a.shape

(3, 4)

In [0]:
a

array([[3., 7., 0., 6.],
       [3., 1., 0., 3.],
       [6., 2., 0., 7.]])

In [0]:
a.resize((2,6))
a

array([[3., 7., 0., 6., 3., 1.],
       [0., 3., 6., 2., 0., 7.]])

In [0]:
a.reshape(3,-1)

array([[3., 7., 0., 6.],
       [3., 1., 0., 3.],
       [6., 2., 0., 7.]])

stacking together different arrays

In [0]:
a=np.floor(10*np.random.random((2,2)))
a

array([[6., 0.],
       [3., 1.]])

In [0]:
b=np.floor(10*np.random.random((2,2)))
b

array([[3., 4.],
       [4., 9.]])

In [0]:
np.vstack((a,b))

array([[6., 0.],
       [3., 1.],
       [3., 4.],
       [4., 9.]])

In [0]:
np.hstack((a,b))

array([[6., 0., 3., 4.],
       [3., 1., 4., 9.]])

In [0]:
from numpy import newaxis
np.column_stack((a,b))

array([[6., 0., 3., 4.],
       [3., 1., 4., 9.]])

In [0]:
a=np.array([4.,2.])
b=np.array([3.,8.])
np.column_stack((a,b))

array([[4., 3.],
       [2., 8.]])

In [0]:
np.hstack((a,b))

array([4., 2., 3., 8.])

In [0]:
a[:,newaxis]

array([[4.],
       [2.]])

In [0]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [0]:
np.hstack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [0]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

Splitting one array into several smaller ones

In [0]:
a=np.floor(10*np.random.random((2,12)))
a

array([[1., 7., 0., 5., 5., 9., 4., 8., 6., 3., 2., 4.],
       [1., 4., 9., 5., 6., 1., 7., 2., 5., 9., 5., 8.]])

In [0]:
np.hsplit(a,3)

[array([[1., 7., 0., 5.],
        [1., 4., 9., 5.]]), array([[5., 9., 4., 8.],
        [6., 1., 7., 2.]]), array([[6., 3., 2., 4.],
        [5., 9., 5., 8.]])]

In [0]:
np.hsplit(a,(3,4))

[array([[1., 7., 0.],
        [1., 4., 9.]]), array([[5.],
        [5.]]), array([[5., 9., 4., 8., 6., 3., 2., 4.],
        [6., 1., 7., 2., 5., 9., 5., 8.]])]

copies and values

no copy at all

In [0]:
a=np.arange(12)
b=a
b is a

True

In [0]:
b.shape=3,4
a.shape

(3, 4)

In [0]:
def f(x):
    print(id(x))
  
id(a)  

139936521104640

In [0]:
f(a) 

139936521104640


view or shallow copy

In [0]:
c=a.view()
c is a

False

In [0]:
c.base is a

True

In [0]:
c.flags.owndata

False

In [0]:
c.shape=2,6
a.shape

(3, 4)

In [0]:
c[0,4]=1234
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [0]:
s=a[: , 1:3]
s[:]=10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

deep copy

In [0]:
d=a.copy()
d is a

False

In [0]:
d.base is a

False

In [0]:
d[0,0]=999
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

Linear algebra 

SImple array opertions

In [1]:
import numpy as np
a=np.array([[1.0,2.0],[3.0,4.0]])
print(a)

[[1. 2.]
 [3. 4.]]


In [2]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [3]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [4]:
u=np.eye(2)
u

array([[1., 0.],
       [0., 1.]])

In [9]:
j=np.array([[0.0,-1.0],[1.0,0.0]])
j@j


array([[-1.,  0.],
       [ 0., -1.]])

In [10]:
np.trace(u)

2.0

In [11]:
y=np.array([[5.],[7.]])
np.linalg.solve(a,y)

array([[-3.],
       [ 4.]])

In [13]:
np.linalg.eig(j)

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))

Introduction

In [16]:
from  array import *
my_array=array('i',[1,2,3,4,5])
for i in my_array:
  print(i)

1
2
3
4
5


In [17]:
my_array[1]

2

In [18]:
my_array[2]

3

In [19]:
my_array[0]

1

In [20]:
my_array.append(6)
my_array

array('i', [1, 2, 3, 4, 5, 6])

In [21]:
my_array.insert(0,0)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6])

In [22]:
my_array.insert(8,7)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7])

In [25]:
my_extend_array=array('i',[8,9,10])
my_array.extend(my_extend_array)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 7, 8, 9, 10, 8, 9, 10, 8, 9, 10])

In [26]:
c=[11,12,13]
my_array.fromlist(c)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 7, 8, 9, 10, 8, 9, 10, 8, 9, 10, 11, 12, 13])

In [27]:
my_array.remove(7)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 8, 9, 10, 8, 9, 10, 11, 12, 13])

In [29]:
my_array.remove(8)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 8, 9, 10, 8, 9, 10, 11, 12, 13])

In [30]:
my_array.remove(9)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 10, 8, 9, 10, 8, 9, 10, 11, 12, 13])

In [31]:
my_array.remove(10)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 8, 9, 10, 11, 12, 13])

In [32]:
my_array.remove(8)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 8, 9, 10, 11, 12, 13])

In [33]:
my_array.remove(9)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 10, 8, 9, 10, 11, 12, 13])

In [34]:
my_array.remove(10)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])

In [35]:
my_array.remove(13)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [36]:
my_array.pop()

12

In [37]:
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

In [38]:
my_array.index(5)

5

In [39]:
my_array.reverse()
my_array

array('i', [11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [40]:
my_array.buffer_info()

(140329472346512, 12)

In [41]:
my_array.count(11)

1

In [51]:
my_char_array=array('b',[ord('g'),ord('e'),ord('e'),ord('k')])
my_char_array

array('b', [103, 101, 101, 107])

In [48]:
my_char_array.tostring()

b'geek'

In [52]:
c=my_array.tolist()
c

[11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [53]:
my_char_array.fromstring("stuff")
my_char_array

array('b', [103, 101, 101, 107, 115, 116, 117, 102, 102])