<a href="https://colab.research.google.com/github/yakshithav/internship/blob/master/pan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The Pandas Series objeccts

In [0]:
import numpy as np
import pandas as pd

data=pd.Series([0.25,0.5,0.75,1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [0]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [0]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [0]:
data[1]

0.5

In [0]:
data[1:3]


1    0.50
2    0.75
dtype: float64

Series as Generalizing numpy array

In [0]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [0]:
data['b']

0.5

In [0]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [0]:
data[5]

0.5

Series as Specialized Dictionary

In [0]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [0]:
population['California']

38332521

In [0]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

Constructing Series Objects

In [0]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [0]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [0]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [0]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])


3    c
2    a
dtype: object

The Pandas Data Frame Objects

In [0]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [0]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [0]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [0]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [0]:
states.columns

Index(['population', 'area'], dtype='object')

Data Frames as Specailized  Dictionary

In [0]:
states['area']


California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

Constructing Data Frames objects 

In [0]:
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

# From List of Dict

In [0]:
data = [{'a': i, 'b': 2 * i}
        for i in range(3)]
pd.DataFrame(data)


a  b
0  0  0
1  1  2
2  2  4

In [0]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [0]:
pd.DataFrame({'population': population,
              'area': area})


population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

From Two Dimensional Numpy  array

In [0]:
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])


foo       bar
a  0.648982  0.390213
b  0.524470  0.002393
c  0.871935  0.099807

From  a Numpy  structured array

In [0]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [0]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

The Pandas Index Object

In [0]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

Index as Immutable array

In [0]:
ind[1]

3

In [0]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [0]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [0]:
ind[1] = 0

TypeError: ignored

Index as ordered set

In [0]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])
indA & indB

Int64Index([3, 5, 7], dtype='int64')

In [0]:
indA | indB

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [0]:
indA ^ indB 

Int64Index([1, 2, 9, 11], dtype='int64')

Data Selection in series

Series in Dicitonary

In [0]:
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [0]:
data['b']

0.5

In [0]:
'a' in data

True

In [0]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [0]:
list(data.items())


[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [0]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [0]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

Series as one-dimensional array

In [0]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [0]:
data[0:2]

a    0.25
b    0.50
dtype: float64

In [0]:
data[(data > 0.3) & (data <0.8)]

b    0.50
c    0.75
dtype: float64

In [0]:
data[['a','e']]

a    0.25
e    1.25
dtype: float64

Indexer : loc , iloc and ix

In [0]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [0]:
data[1]

'a'

In [0]:
data[1:3]

3    b
5    c
dtype: object

In [0]:
data.loc[1]

'a'

In [0]:
data.loc[1:3]

1    a
3    b
dtype: object

In [0]:
data.iloc[1]

'b'

In [0]:
data.iloc[1:3]

3    b
5    c
dtype: object

Data Selection in DataFrame

DataFrame as a dictionary

In [0]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [0]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [0]:
data['pop']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: pop, dtype: int64

In [0]:
data.area


California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [0]:
data.area is data['area']

True

In [0]:
data.pop is data['pop']

False

In [0]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

DataFrame as two-dimensional array

In [0]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [0]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [0]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [0]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [0]:
data.iloc[:3, :2]


area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [0]:
data.loc[:'Illinois', :'pop']


area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [0]:
data.ix[:3, :'pop']

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [75]:
data.loc[data.density > 100, ['pop', 'density']]


pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [76]:
data.iloc[0, 2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

Additional indexing conventions

In [77]:
data['Florida':'Illinois']


area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [78]:
data['Florida':'Illinois']


area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [79]:
data[data.density > 100]


area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

# **Operating on pandas**

Index Preservation


In [80]:
import pandas as pd
import numpy as np

rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [81]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [82]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [83]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

Index Alignment


Index alignment in Series



In [86]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

population / area


Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [87]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [88]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B


0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [89]:
A.add(B, fill_value=0)


0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

Index alignment in DataFrame

In [90]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('AB'))
A

A   B
0  1  11
1  5   1

In [91]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('BAC'))
B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [92]:
A + B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [93]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

Operations Between DataFrame and Series

In [94]:
A = rng.randint(10, size=(3, 4))
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [95]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])

In [96]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]


Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [97]:
df.subtract(df['R'], axis=0)


Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [98]:
df.subtract(df['R'], axis=0)


Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [99]:
halfrow = df.iloc[0, ::2]
halfrow


Q    3
S    2
Name: 0, dtype: int64

In [100]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN  2.0 NaN
2  3.0 NaN  1.0 NaN

**Handling Missing data**


Trade-Offs in Missing Data Conventions

Pythonic missing data

In [101]:
import numpy as np
import pandas as pd
vals1 = np.array([1, None, 3, 4])
vals1


array([1, None, 3, 4], dtype=object)

In [102]:
for dtype in ['object', 'int']:
    print("dtype =", dtype)
    %timeit np.arange(1E6, dtype=dtype).sum()
    print()


dtype = object
10 loops, best of 3: 82.3 ms per loop

dtype = int
100 loops, best of 3: 2.29 ms per loop



In [103]:
vals1.sum()

TypeError: ignored

Missing numerical data

In [104]:
vals2 = np.array([1, np.nan, 3, 4]) 
vals2.dtype

dtype('float64')

In [105]:
1 + np.nan

nan

In [106]:
0 *  np.nan

nan

In [107]:
vals2.sum(), vals2.min(), vals2.max()

(nan, nan, nan)

In [108]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)


(8.0, 1.0, 4.0)

NaN and None in Pandas

In [109]:
pd.Series([1, np.nan, 2, None])


0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [110]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int64

In [111]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

Operating on Null Values

Detecting null values

In [112]:
data = pd.Series([1, np.nan, 'hello', None])
data.isnull()


0    False
1     True
2    False
3     True
dtype: bool

In [113]:
data[data.notnull()]

0        1
2    hello
dtype: object

Dropping null values

In [114]:
data.dropna()

0        1
2    hello
dtype: object

In [115]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [116]:
df.dropna()


0    1  2
1  2.0  3.0  5

In [117]:
df.dropna(axis='columns')

2
0  2
1  5
2  6